### PR TITLE
feat: flatten

### PR DESCRIPTION
**Pull request by jthomerson**

### CODE REVIEW

**Comment by jthomerson** [comment]
FYI @yokuze @jimjenkins5 @onebytegone

**Comment by jthomerson** [comment]
FYI @lukelafountaine

**Comment by jthomerson** [comment]
Actually, this is kinda clunky if you have an array of arrays, which is probably more common than the variadic arguments I allowed for. 

```ts
// i.e. this doesn't work
const strings: string[] = flatten([ [ 'a', 'b' ], [ 'c', 'd' ] ]);
// you have to do this instead (add the spread):
const strings: string[] = flatten(...[ [ 'a', 'b' ], [ 'c', 'd' ] ]);
```

And, it doesn't handle nested arrays like Underscore did.

Also, the implementation is not great for huge arrays. That part I can easily revisit, but I'm actually not sure how to handle the types for the first two problems mentioned above. Any pointers on that @jimjenkins5 @yokuze @onebytegone @lukelafountaine?

**Comment by yokuze** [comment]
After the work that @jimjenkins5 is doing to upgrade us to Babel and the newest version of TypeScript is done, we should have access to the ES2019 [`Array#flat`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat) method: https://github.com/microsoft/TypeScript/blob/master/src/lib/es2019.array.d.ts#L32

We should use that built-in method where possible, and consider removing this function from the toolbox.

**Pull request merged**
