### PR TITLE
config: enable renovatebot

### PR DESCRIPTION
**Pull request by onebytegone**

### CODE REVIEW

**Comment by crgwbr** [comment]
@onebytegone Any particular reason why we'd put these settings directly in this repo, vs. making a new (reusable) preset and using that here?

**Comment by onebytegone** [comment]
@crgwbr By preset, do you mean adding something to @silvermine/standardization that all the repos can then use? Eventually, that's the goal. However, since we're not completely sure this is the right config, I wanted to try it out first before putting this in standardization.

**Comment by crgwbr** [comment]
@onebytegone 

> By preset, do you mean adding something to @silvermine/standardization that all the repos can then use? 

Yeah, though the docs recommend putting it in its own repo. Here's an example:

- Preset: https://gitlab.com/thelabnyc/renovate-config/-/blob/master/library.json
- Usage: https://gitlab.com/thelabnyc/thelab-db/-/blob/master/renovate.json

See also, docs: https://docs.renovatebot.com/config-presets/

**Comment by onebytegone** [comment]
@crgwbr Ahhh, makes sense. [silvermine/renovate-config](https://github.com/silvermine/renovate-config) has been created and this PR updated.

**Comment by crgwbr** [comment]
Awesome! LGTM

**Review by crgwbr — APPROVED** [review]

**Pull request merged**
